### ISSUE TITLE
Undocumented C specific setting

### ISSUE THREAD

**Issue by leksak** [Eeemil/dotfiles#2]
`(setq safe-local-variable-values (quote ((flycheck-gcc-language-standard . gnu99))))`

**Comment by Eeemil** [comment]
In Emacs, one can define [local per-file variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html#Specifying-File-Variables), so that a certain variable is set in Emacs every time a certain file is opened.

However, by default, Emacs does not load all kinds of stupid stuff that stupid people put in files. This line, however, tells us that setting the variable "flycheck-gcc-language-standard" to "gnu99" is always considered safe and Emacs will not annoy me with warnings or prompt me if I want to set the variable.

**Comment by Eeemil** [comment]
Fixed in 1d1c768
